# Generated by Django 3.2.7 on 2023-07-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatresidence', '0005_gym_booking_hall_booking_pool_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=100)),
                ('s_name', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
